---
# Minion configuration schema
#
# See the readme MINION_CONFIG_SCHEMA_README.md for more information.

# Version of Minion this schema configuration is applicable to
version: "27.0.0"

# The root set of categories configurable on a Minion container. Ordering here is used only to determine order for
# display purposes.
categories:
  # General
  - name: "general"
    label: "General"
    description: "General Minion settings."
    config:
      - name: "instance-id"
        type:
          name: "string"
          validation: "TODO"
        label: "Core Instance Id"
        description: "Identifier for the Core instance used as queue prefix in the message broker."
        key: "/org.opennms.instance.id"
        example: "OpenNMS"
      - name: "system-properties"
        type:
          name: "properties"
        label: "System Properties"
        description: "Set generic Java system properties"
        key: "/system/properties"
        example: "jaeger-agent-host: my-jaeger-host"
      - name: "server-certificates"
        type:
          name: "collection"
          strategy: "indexed"
          items:
            label: "Certificate Name"
            type:
              name: "string"
        label: "Server Certificates"
        description: "TLS certificates for public communication endpoints."
        key: "/server-certs"
        example: "TODO"
    categories:
      # General :: Controller
      - name: "controller"
        label: "Minion Controller"
        description: "Minion controller configuration for a location and communication endpoints."
        config:
          - name: "location"
            type:
              name: "string"
              validation: "TODO"
            label: "Location"
            description: "Name of the location the Minion is deployed"
            key: "/location"
            example: "my-remote-office-nyc"
          - name: "id"
            type:
              name: "string"
              validation: "TODO"
            label: "Minion Id"
            description: "A unique Minion identifier in the location."
            key: "/id"
            example: "id: my-minion-nyc"
          - name: "broker-url"
            type:
              name: "url"
            label: "The message broker URL"
            description: "Message broker connection URL"
            key: "/broker-url"
            example: "ActiveMQ: failover:[tcp,ssl]://my-activemq-ip:61616, Kafka: broker-01:9092, broker-02:9092"
          - name: "http-url"
            type:
              name: "url"
            label: "Core base URL"
            description: "The Core web application base URL."
            key: "/http-url"
            example: "http://my-opennms-instance-ip:8980/opennms"
  # Dominion
  - name: "dominion"
    label: "Dominion"
    description: "Dominion configuration"
    categories:
      # Dominion :: gRPC
      - name: "grpc"
        label: "gRPC"
        description: "gRPC endpoint"
        config:
          - name: "host"
            type:
              name: "host"
            label: "Host"
            description: "TODO"
            key: "/dominion/grpc/host"
            example: "TODO"
          - name: "port"
            type:
              name: "port"
            label: "Port"
            description: "TODO"
            key: "/dominion/grpc/port"
            example: "TODO"
          - name: "client-secret"
            type:
              name: "string"
            label: "Client Secret"
            description: "TODO"
            key: "/dominion/grpc/client-secret"
            example: "TODO"
      # Dominion :: SCV
      - name: "scv"
        label: "Secure Credentials Vault"
        description: "TODO"
        config:
          - name: "provider"
            type:
              name: "string"
            label: "Provider"
            description: "TODO"
            key: "/scv/provider"
            example: "TODO"
  # Karaf
  - name: "karaf"
    label: "Karaf"
    description: "Karaf configuration"
    categories:
      # Karaf :: Management
      - name: "management"
        label: "Management"
        description: "Configuration for Karaf JMX management access"
        categories:
          # Karaf :: Management :: RMI
          - name: "rmi"
            label: "RMI"
            description: "Configure remote method invocation (RMI)"
            config:
              - name: "registry-host"
                type:
                  name: "host"
                label: "Registry Host"
                description: "RMI registry host IP address"
                key: "/karaf/management/rmi/registry/host"
                example: "127.0.0.1"
              - name: "registry-port"
                type:
                  name: "port"
                label: "Registry Port"
                description: "RMI listening TCP port"
                key: "/karaf/management/rmi/registry/port"
                example: "1299"
              - name: "server-host"
                type:
                  name: "host"
                label: "Server Host"
                description: "RMI server host IP address seen by the client"
                key: "/karaf/management/rmi/server/host"
                example: "127.0.0.1"
              - name: "server-port"
                type:
                  name: "port"
                label: "Server Port"
                description: "RMI server TCP port"
                key: "/karaf/management/rmi/server/port"
                example: "45444"
      # Karaf :: Shell
      - name: "shell"
        label: "Shell"
        description: "Karaf Shell access configuration"
        categories:
          # Karaf :: Shell :: SSH
          - name: "ssh"
            label: "SSH"
            description: "Karaf SSH configuration"
            config:
              - name: "host"
                type:
                  name: "host"
                label: "Host"
                description: "Listening IP address for the SSH service"
                key: "/karaf/shell/ssh"
                example: "0.0.0.0"
              - name: "port"
                type:
                  name: "port"
                label: "Port"
                description: "TCP listening port the SSH service"
                key: "/karaf/shell/port"
                example: "8201"
  # Minion Environment
  - name: "environment"
    label: "Environment"
    description: "Minion Java environment"
    config:
      - name: "java-opts"
        type:
          name: "collection"
          strategy: "indexed"
          items:
            label: "Option"
            type:
              name: "string"
        label: "JVM Options"
        description: "Additional Java options"
        key: "/process-env/java-opts"
        example: "-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=7896"
  # IPC Configuration
  - name: "ipc"
    label: "IPC"
    description: "Core, Minion and Sentinel distributed inter process communication (IPC) settings"
    categories:
      # IPC Configuration :: AWS
      - name: "aws"
        label: "AWS"
        description: "Amazon Web Services Simple Queue Service (AWS SQS) configuration"
        config:
          - name: "properties"
            type:
              name: "properties"
            label: "Properties"
            description: "AWS SQS properties"
            key: "/aws"
            example: "aws_region: us-east-1, aws_access_key_id: xxxxxx or aws_secret_access_key: yyyyyy"
        categories:
          # IPC Configuration :: AWS :: SQS
          - name: "sqs"
            label: "SQS"
            description: "IPC messaging configuration for AWS SQS"
            config:
              - name: "properties"
                type:
                  name: "properties"
                label: "Properties"
                description: "AWS SQS IPC properties"
                key: "/ipc/sqs"
                example: "sink.MaximumMessageSize: 262144"
      # IPC Configuration :: gRPC
      - name: "grpc"
        label: "gRPC"
        description: "gRPC for IPC configuration"
        config:
          - name: "host"
            type:
              name: "host"
            label: "Host"
            description: "gRPC host endpoint, typcally the same Core instance"
            key: "/ipc/grpc/host"
            example: "my-opennms-instance-ip"
          - name: "port"
            type:
              name: "port"
            label: "gRPC TCP port"
            description: "gRPC TCP port the server is listening"
            key: "/ipc/grpc/port"
            example: "8990"
          - name: "properties"
            type:
              name: "properties"
            label: "Properties"
            description: "Additional gRPC configuration properties for IPC gRPC"
            key: "/ipc/grpc"
            example: "max.message.size: 10485760"
      # IPC Configuration :: RPC
      - name: "rpc"
        label: "RPC"
        description: "TODO"
        categories:
          # IPC Configuration :: RPC :: Kafka
          - name: "kafka"
            label: "Kafka"
            description: "TODO"
            config:
              - name: "bootstrap-servers"
                type:
                  name: "set"
                  strategy: "concat"
                  items:
                    label: "Server"
                    type:
                      name: "host-with-port"
                    separator: ","
                label: "Bootstrap Servers"
                description: "Kafka bootstrap servers for IPC RPC"
                key: "/ipc/rpc/kafka/bootstrap.servers"
                example: "TODO"
              - name: "properties"
                type:
                  name: "properties"
                label: "Properties"
                description: "Additional Kafka configuration properties for IPC RPC"
                key: "/ipc/rpc/kafka"
                example: "TODO"
      # IPC Configuration :: Sink
      - name: "sink"
        label: "Sink"
        description: "TODO"
        config:
          - name: "offheap"
            type:
              name: "properties"
            label: "Off Heap"
            description: "TODO"
            key: "/ipc/sink/offheap"
            example: "TODO"
        categories:
          # IPC Configuration :: Sink :: Kafka
          - name: "kafka"
            label: "Kafka"
            description: "TODO"
            config:
              - name: "bootstrap-servers"
                type:
                  name: "set"
                  strategy: "concat"
                  items:
                    label: "Server"
                    type:
                      name: "host-with-port"
                    separator: ","
                label: "Bootstrap Servers"
                description: "Kafka bootstrap servers for IPC Sink"
                key: "/ipc/sink/kafka/bootstrap.servers"
                example: "TODO"
              - name: "properties"
                type:
                  name: "properties"
                label: "Properties"
                description: "Additional Kafka configuration properties for IPC Sink"
                key: "/ipc/sink/kafka"
                example: "TODO"
  # Netmgt
  - name: "netmgt"
    label: "Network Management"
    description: "TODO"
    categories:
      # Netmgt :: Traps
      - name: "traps"
        label: "Traps"
        description: "TODO"
        config:
          - name: "properties"
            type:
              name: "properties"
            label: "Properties"
            description: "TODO"
            key: "/netmgt/traps"
            example: "TODO"
      # Netmgt :: Syslog
      - name: "syslog"
        label: "Syslog"
        description: "TODO"
        config:
          - name: "properties"
            type:
              name: "properties"
            label: "Properties"
            description: "TODO"
            key: "/netmgt/syslog"
            example: "TODO"
  # Web
  - name: "web"
    label: "Web"
    description: "TODO"
    categories:
      # Web :: Jetty
      - name: "jetty"
        label: "Jetty"
        description: "TODO"
        config:
          - name: "http-listen-port"
            type:
              name: "port"
            label: "HTTP Listen Port"
            description: "Jetty HTTP listen port"
            key: "/jetty/web/port"
            example: "TODO"
          - name: "listen-address"
            type:
              name: "set"
              strategy: "concat"
              items:
                label: "Listen Address"
                type:
                  name: "host"
                separator: ","
            label: "Listen Address"
            description: "Jetty listen addresses"
            key: "/jetty/web/host"
            example: "TODO"
  # Telemetry
  - name: "telemetry"
    label: "Telemetry"
    description: "TODO"
    categories:
      # Telemetry :: Flows
      - name: "flows"
        label: "Flows"
        description: "TODO"
        config:
          - name: "flow-listener-def"
            type:
              name: "objects"
              fields:
                - name: "listener-name"
                  label: "Listener Name"
                  type:
                    name: "string"
                    validation: "TODO"
                - name: "class-name"
                  label: "Class Name"
                  type:
                    name: "string"
                    validation: "TODO"
                - name: "parameters"
                  label: "Parameters"
                  type:
                    name: "properties"
              index-type: "field"
              index-field: "listener-name"
            label: "Flow Listener Definition"
            description: "TODO"
            key: "/telemetry/flows/listeners"
            example: "TODO"
          - name: "flow-parser-def"
            type:
              name: "objects"
              fields:
                - name: "parser-name"
                  label: "Parser Name"
                  type:
                    name: "string"
                    validation: "TODO"
                - name: "class-name"
                  label: "Class Name"
                  type:
                    name: "string"
                    validation: "TODO"
                - name: "parameters"
                  label: "Parameters"
                  type:
                    name: "properties"
              index-type: "field"
              index-field: "parser-name"
            label: "Flow Parser Definition"
            description: "TODO"
            key: "/telemetry/flows/parsers"
            example: "TODO"
        categories:
          # Telemetry :: Flows :: Single Port Listener
          - name: "single-port-listener"
            label: "Single Port Listener"
            description: "TODO"
            config:
              - name: "enabled"
                type:
                  name: "boolean"
                label: "Enable Single Port Listener"
                description: "TODO"
                key: "/telemetry/flows/single-port-listener/enabled"
                example: "TODO"
              - name: "name"
                type:
                  name: "string"
                  validation: "TODO"
                label: "Name"
                description: "TODO"
                key: "/telemetry/flows/single-port-listener/name"
                example: "TODO"
              - name: "parameters"
                type:
                  name: "properties"
                label: "Parameters"
                description: "TODO"
                key: "/telemetry/flows/single-port-listener/parameters"
                example: "TODO"
              - name: "parser-parameters"
                type:
                  name: "properties"
                label: "Parser Parameters"
                description: "TODO"
                key: "/telemetry/flows/single-port-listener/parser-parameters"
                example: "TODO"
